baseURL = "https://wkz.github.io/"
languageCode = "en-us"
title = "wkz"
theme = "hugo-tufte"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4

[params]
subtitle = "/* You are not expected to understand this */"
copyrightHolder = "Tobias Waldekranz"
github = "wkz"
twitter = "776b7a"

# [taxonomies]
#    tag = "tags"
#    category = "categories"

# [[menu.main]]
# url = "/categories"
# name = "Categories"
# weight = 2
# [[menu.main]]
# url = "/tags"
# name = "Tags"
# weight = 3
# [[menu.main]]
# url = "/posts"
# name = "Archive"
# weight = 1
# [[menu.main]]
# url = "/index.xml"
# name = "RSS Feed"
# weight = 4
